### ISSUE TITLE
Links

### ISSUE THREAD

**Issue by ronfrankhill** [Mr-Kodi/repository.fenomscrapers#11]
Is it possible for fenomscrapers to get scrapers to locate or pull links for a TV series call Graves which is from Epix. Also another TV series call Get Shorty from Epix. Both aired in 2016. Please. I tried many times but I am not getting any links to play. The other add-ons is getting it e.g. Alvin, Revolution.

**Comment by 123Venom** [comment]
I used your show Graves to run some tests.  There's no cached torrents for that found in Fen, Venom, or Seren I could find.  This is not a scraper issue.  If you allow uncached torrents to be shown in Fen or Venom you'll see it pulls in plenty of sources.  You'll need to cache that yourself since it's rather unpopular that nobody is bothering to cache it.

I did a quick test of Get Shorty s01...Fen and Venom both returned plenty of cached sources as pack files and single episodes.  There's not a scraper issue to be seen here with FenomScrapers or the addons themselves for that matter.
