### ISSUE TITLE
Can we add a specific public torrent site to scraper list?

### ISSUE THREAD

**Issue by onlytanmoy** [Mr-Kodi/repository.fenomscrapers#17]
Hiya, hope you are doing well.
I was advised by Tikipeter on my ticket (https://github.com/Tikipeter/repository.tikipeter/issues/488) to contact you on my request to add a torrent source site to fenomscrapers :)
Actually this site shows 1080p cached RD links for my regional contents while Fen & Venom shows only 720p link for the same content. So I was wondering if you can add it to fenomscrapers/venomscrapers, let me know.

**Comment by 123Venom** [comment]
and that source site would be what url exactly?

**Comment by onlytanmoy** [comment]
here you go mate

https://torrentproject2.com/

**Comment by 123Venom** [comment]
Unfortunately that's no good for two reasons.  The first being it's a two request site and I've pretty much come to the point of no interest in adding more of them as they're very slow.  The query results does not contain the magnet nor even the hash to form the magnet so each item would need to be a second request.  That second page the links are behind **mylink.vc** so that's another no..lol.  Sorry man.

**Comment by onlytanmoy** [comment]
No worries mate, thanks for checking out for me 🙂

**Comment by 123Venom** [comment]
I got a little bored today so I sampled [torrentproject2.com](torrentproject2.com) .  It's not that bad but again since it takes 2 requests to fetch magnets it's slower than a good majority of our scrapers.  Prob not one I will use myself as I use 6-7 max and favor the single request faster scrapers.  There's a help file in the torrent category when you pull up the settings that I've written some vital info on like, api torrent, single request and 2 request sites.

This one will be included in next update.

**Comment by onlytanmoy** [comment]
Next update eagerly awaited 🙂 Thank you.

**Comment by 123Venom** [comment]
we lost skytorrents a few versions ago and looks like btdb is now gone.  Both domains now loading some **Onionflix** site..lol
[https://btdb.eu](https://btdb.eu)
[https://btdb.unblockit.ltd](https://btdb.unblockit.ltd)

**Comment by onlytanmoy** [comment]
@123Venom TP2 is working great, many thanks for adding it mate 👍

**Comment by onlytanmoy** [comment]
@123Venom hiya, please can you check if it will be possible to add https://btdig.com/  ?
I will be happy to create a new ticket for this request once you confirm. 😊
Have a great Sunday.

**Comment by Nuklear92** [comment]
> @123Venom hiya, please can you check if it will be possible to add https://btdig.com/  ?
> 
> I will be happy to create a new ticket for this request once you confirm. 😊
> 
> Have a great Sunday.

Fenomscrapers already has or had this scraper. And trust me it's not that good, A4kscrapers scrapers has it and I even disable it because the results from it doesn't impress me over others. I used to be one of those who root for more scrapers thinking more was better, after I slowly realize that after 10 scrapers or even less you just start adding up wasted time for the scraping process to finish up as the scraper will just be getting duplicates and the more duplicates the more it has to remove urls at the end of the process. No matter how many scrapers you have enabled the truth is the scraper will always get all of the available cached torrents from the first 5-10 the rest is just added time. Sometimes, it could probably find 1 or 2 more links but usually the major high quality links will retrieved from the first 5. 

This is why I rather have 10 maximum sources enabled specially the best ones and get all the links in matter of 5-6 seconds than having 20+ enabled sources and get the same amount of sources with like 5 seconds of wasted time. 🤷‍♂️

**Comment by onlytanmoy** [comment]
@Nuklear92 hmm yeah you are right, that makes sense. Sometimes less is better, quality over quantity any day 😊thanks for the great explanation 💯

**Comment by 123Venom** [comment]
@Nuklear92 very well written and on point!  I use 6-7 scrapers and that's plenty.
  Now btdig we had and was removed a month ago because of a new capture, to which I still have the log data from it.  Is it still functional in Seren?

```
[2021-05-21 00:14:00] [COLOR red][ FENOMSCRAPERS INFO ][/COLOR]: url = https://www.btdig.com/search?q=Interstellar+2014
<title>Attention Required!</title>
</head>
<!-- 73.126.108.32 @ AS7922 -->
<!-- ifn5 -->
<!-- A19 -->
       One more step
        Please complete the security check to access
       </span>
 <script src="https://www.google.com/recaptcha/api.js?onload=onloadCallback&render=explicit" async defer></script>
</body>
</html>
 (NORMALIZED by log_utils.log())```

**Comment by Nuklear92** [comment]
> @Nuklear92 very well written and on point!  I use 6-7 scrapers and that's plenty.
> 
>   Now btdig we had and was removed a month ago because of a new capture, to which I still have the log data from it.  Is it still functional in Seren?
> 
> 
> 
> ```
> 
> [2021-05-21 00:14:00] [COLOR red][ FENOMSCRAPERS INFO ][/COLOR]: url = https://www.btdig.com/search?q=Interstellar+2014
> 
> <title>Attention Required!</title>
> 
> </head>
> 
> 
> 
> 
> 
> 
> 
>        One more step
> 
>         Please complete the security check to access
> 
>        </span>
> 
>  <script src="https://www.google.com/recaptcha/api.js?onload=onloadCallback&render=explicit" async defer></script>
> 
> </body>
> 
> </html>
> 
>  (NORMALIZED by log_utils.log())```

To my knowledge, yes I think it still works in Seren, I'll double check in a moment and let you know.

**Comment by Nuklear92** [comment]
@123Venom you're right, it's not working anymore in a4kscrapers either. I double checked the website and it seems to be prompting a captcha everytime you make a search. I'll let the dev know as well so he removes it. Man, suddenly a lot of sites are getting either shut down or under captcha and cloudflare. 😤😩
