### ISSUE TITLE
Torrents

### ISSUE THREAD

**Issue by ronfrankhill** [Mr-Kodi/repository.fenomscrapers#19]
I don't know if you can benefit from this but here's a site link to different mirror torrents sites https://www.firesticktricks.com/torrent-sites.html

**Comment by Nuklear92** [comment]
Most of the public sites here are already present within the scraper. The private torrent sites I don't believe they can be added since they require actual active accounts to be made in other to see their torrents, and I believe that's via invitation only from someone who has an active account from the specific site. Then the mods from that website needs to approve it, which they're quite picky. 

As I mentioned in a previous post about adding more sites. There's no need to, Fenomscrapers already has more sources than required for pulling links. The more sites you add it's just more wasted scraping time for pulling duplicate links. It would be another story if the scraper had like 5-10 sources only which in theory is more than enough to pull all of the available links from titles. 🤷‍♂️ you can have enabled 20+ sources and you'll be getting all of your links within the first 5-6 sources being scraped, the rest is just wasted time and lots of duplicates links to be removed after the scraping process is finished.

**Comment by ronfrankhill** [comment]
Okay. Thanks for the update. I kn

**Comment by Nuklear92** [comment]
> Okay. Thanks for the information. I know sometimes most torrents constantly changing their URL but I understand. Thanks again.

No worries, Fenomscrapers dev is always aware when a url changes or it's dead and quickly pushes an scraper update. 😉
