### ISSUE TITLE
No Sources Found since v1.5.8

### ISSUE THREAD

**Issue by iCanuck** [Mr-Kodi/repository.fenomscrapers#25]
Since fenomscrapers v1.5.8 get 'sources not found' last working fenomscrapers for me is v1.5.7. Tested on K18 & K19.

**Comment by iCanuck** [comment]
> 
> 
> Since fenomscrapers v1.5.8 get 'sources not found' last working fenomscrapers for me is v1.5.7. Tested on K18 & K19.

I see now with the changes to v1.5.8 it is only compatible with K19. How about adding a dependency for python 3 or xbmc gui v5.15.0 so people still running K18 don't receive the update to v1.5.8+

**Comment by 123Venom** [comment]
what addon?  FS is compatible with 18 and 19.  The problem is FS v1.5.8 was a re-write of the scraper call methods so any addon using FS needs to be updated for the change.  Kodi 19 versions were updated for Fen and Venom compatibility but I do not believe either is doing Kodi 18 updates anymore so unless they do it will no longer work.
