### ISSUE TITLE
Issue detecting 4K season pack regardless of being cached in Debrid services

### ISSUE THREAD

**Issue by Nuklear92** [Mr-Kodi/repository.fenomscrapers#30]
The TV Show **Ozark** specially the **Season 4: Part 1** 4K Packs aren't being recognized by Fenomscrapers. I already tried disabling/enabling filters and trying multiple other ways to see if there was an option blocking the 4K packs for being shown in FEN. Eventually I installed Venom as well made sure even all restrictions/filters were OFF from Fenomscrapers and even there the 4K Season Pack from the Season 4 of Ozark isn't recognized either.

Hopefully, this can be corrected for the next Fenomscrapers update/patch. 👍

**Comment by 123Venom** [comment]
That's actually more by intended design by the addon devs and not from FS so there's nothing to correct when it was designed that way.  The addons are not making pack file requests for seasons that are still airing, if they were then FS DOES return those 4k `Part.1` sources.  The intent was to save scrape time and to scrape for pack files of a season that is still airing is more than likely not going to return sources and often may even produce bad results with fools that upload incomplete pack files with missing episodes, seen a ton of that stuff.  This was really a common happy ground agreed upon by the devs.  You just found a more rare case where they split the season mid way into packs and are valid cases.  I can not speak for the Fen dev but being the Venom dev I'm not sure sure I'm willing to gamble on making pack file requests for seasons still airing.  It would cause seasons with 1 aired episode to scrape for pack files and slow the process down considerably for the rare chance they might have broken up the season like Ozark.

Here's how you can spot the condition I speak of.  Using Fen and FenomScrapers on the default scrapers when you scrape Ozark S03E01 you many notice the scraper dialog box indicates a higher provider count, like 16.  When you scrape S04E01 the provider count started at 7 because it is not making pack file requests to FS for the season that is still airing.

I did for the heck of it make a quick code change to Venom to alter this behavior to verify FS does indeed return these partial packs.

<img width="1707" alt="Part1" src="https://user-images.githubusercontent.com/46383815/158943395-08507a25-94de-4dd3-9346-b89590f7f142.PNG">

It does but honestly I just do not trust it for every day use and returning a bunch of rubbish.  I may consider adding a setting to allow you at your own will to perform these pack file scrapes for still airing seasons....I'd just under most cases not advise it.  I'd make the default stick to the current scrape method though and you'd be on your own with these cases.  I'm going to chat this one round a few groups to see the general feeling.

**Comment by 123Venom** [comment]
Here's a prime example what I tried to explain.  **The Walking Dead** S11.  The code change I made above now forces that season, that is still airing, to scrape for pack files.  No partial packs were returned like Ozark so I needlessly scraped for those and can see the slow down doing this introduces.  I'm really leaning towards not changing anything for this.  

I think the best thing to do for these rare cases is to manually add that 4k stream too your cloud.  I returned the code to it's official state, added the 4k Part1 pack to my AD cloud and rescraped.  It shows up fine.

<img width="1200" alt="cloud" src="https://user-images.githubusercontent.com/46383815/158961125-3e0bf57a-33f1-4185-ae82-d85ae0737e61.PNG">

**Comment by Nuklear92** [comment]
Oh, silly me! It's all good, been quite a long time since I don't manually add season packs to watch directly from Cloud. Since I'm so used to just doing a quick scrape and watch from there. 

Thanks for the heads up on showing me that it does show the pack if add it to my RD account. Usually since FEN by default doesn't check Cloud and you manually have to enable it within the settings. It never crossed my mind to check upon that and I just kept enabling and disabling certain filters, plus trying different sources, etc. within Fenomscrapers settings addon 😅. 

You can keep the official code settings for sure, I wouldn't like to make a mess overall either. just to make one TV Show recognize a Season Pack that's split on 2 parts. 

Thanks again, and my apologies for wasting your time on this matter.
