### ISSUE TITLE
No Results Using FenomScapers

### ISSUE THREAD

**Issue by pewkodi** [Mr-Kodi/repository.fenomscrapers#5]
I tried to add fenomscrapers as the source for my addon instead of openscrapers. Do you have to have a furk account or should a debrid account just like openscapers. 

Note: it looks to load the sources but then instantly quit. I looked at the logs but saw nothing.

Thanks

**Comment by Tikipeter** [comment]
I'm afraid there's more to it than what is in the `readme`. What addon are you trying to adapt?

**Comment by pewkodi** [comment]
This is addon similar to exodus.

**Comment by bjbca** [comment]
A premium account like real debrid is required and maybe now the exo fork needs to be compatible with myaccounts addon also ?

**Comment by Tikipeter** [comment]
> This is addon similar to exodus.

Check out the Venom addon's code and how it interacts with Fenomscrapers.

There is no need for any particular account to get it to work, but since they are scrapers that will predominantly return torrent or premium filehoster results, it would be a good idea to use a debrid service.

Start with the code to get movie results, as that is the least changed from the Exo forks. The TV Show changes are more involved.

As I said though, there is a fair few differences compared to old scraper packages, so take your time looking through the code and implementing the changes.
